baseURL = "https://www.depthbuffer.uk/"
languageCode = "en-GB"
title = "Depthbuffer"
disableKinds = ["sitemap", "RSS"]
summaryLength = "40"

[markup]
    [markup.highlight]
        noClasses = false
    [markup.tableOfContents]
        ordered = false
        startLevel = 2

[privacy]
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true

[social]
    twitter = "DepthbufferM"

[taxonomies]
    tag = 'tags'
