baseURL = "https://www.depthbuffer.uk/"
languageCode = "en-GB"
title = "Depthbuffer"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "sitemap", "RSS"]
summaryLength = "40"

[markup]
    [markup.highlight]
        noClasses = false

[privacy]
    [privacy.twitter]
        enableDNT = true
    [privacy.youtube]
        privacyEnhanced = true

[social]
    twitter = "DepthbufferM"
