baseURL = "https://www.depthbuffer.uk/"
languageCode = "en-GB"
title = "Depthbuffer"
disableKinds = ["taxonomy", "taxonomyTerm", "category", "sitemap", "RSS", "section"]

[markup]
    [markup.highlight]
        noClasses = false
